[package]
name = "blipmq_chaos"
version.workspace = true
edition.workspace = true
authors.workspace = true
description = "BlipMQ chaos testing utilities"
license.workspace = true

[dependencies]
tokio = { workspace = true, features = ["fs", "net", "time", "macros"] }
rand = "0.8"
